export const FETCH_LIST_PRODUCT = "FETCH_LIST_PRODUCT";

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";

export const EDIT_PRODUCT = "EDIT_PRODUCT";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const FETCH_LIST_MANUFACTURER = "FETCH_LIST_MANUFACTURER";

export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";
